### ISSUE TITLE
Spanish translation of outline/setup_osx.md file

### ISSUE THREAD

**Issue by davecaos** [ClojureBridgeBA/curriculum#2]
This file https://github.com/ClojureBridgeBA/curriculum/blob/gh-pages/outline/setup_osx.md

**Comment by marcote** [comment]
@davecaos I can do this one.

**Comment by davecaos** [comment]
Thanks @marcote !

**Comment by allentiak** [comment]
@marcote Any news regarding this one?

**Comment by marcote** [comment]
@allentiak Estoy a mil en el laburo (en Seattle) pero este finde lo tengo libre y me pongo a full. Está al 30%.

**Comment by allentiak** [comment]
¡Buenísimo, @marcote! Avisá en caso de que te haga falta ayuda.
(Siempre es una opción hacer un `push` a medida que vas haciendo los commits, así tenemos una idea acerca de tu progreso ;-)

**Comment by marcote** [comment]
Posta no pensé que iba a estar tan hasta las manos.

**Comment by nberger** [comment]
Fixed by #20
