### ISSUE TITLE
Spanish translation of cheatsheet-quil.md and cheatsheet.md

### ISSUE THREAD

**Issue by davecaos** [ClojureBridgeBA/curriculum#4]
Those files gh-pages/outline/cheatsheet-quil.md 
                gh-pages/outline/cheatsheet.md

**Comment by gnandretta** [comment]
I can take care of this one

**Comment by allentiak** [comment]
@gnandretta Any news regarding this one?

**Comment by gnandretta** [comment]
@allentiak I'm almost done, will push it tomorrow, Saturday tops.

**Comment by allentiak** [comment]
Great, @gnandretta ! Please let me know in case you need a hand with this.
(It is always an option to push your commits as-you-go, so we know about your progress ;-)
